<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dfctl</AssemblyName>
    <RootNamespace>DocumentForge.Ctl</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DocumentForge.Engine\DocumentForge.Engine.csproj" />
  </ItemGroup>
</Project>
